version: '3.8'

services:
  backend:
    build: './backend'
    container_name: backend
    restart: 'always'
    ports:
      - '8080:8080'
    depends_on:
      - mongo
      - mongoexport
  
  frontend:
    build: 
      context: './frontend'
      dockerfile: Dockerfile.dev
    container_name: frontend
    restart: 'always'
    ports:
      - '5173:5173'
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
  
  mongo:
    image: mongo:latest
    container_name: my_mongo
    restart: 'always'
    ports:
      - "27017:27017"
    volumes:
      - ./dump:/dump
    command: mongod --bind_ip_all

  mongoimport:
    image: mongo:latest
    depends_on:
      - mongo
    volumes:
      - ./dump:/dump
    entrypoint: >
      bash -c "
        echo '⏳ Ожидание старта MongoDB...';
        sleep 5;

        ARCHIVE=/dump/shop-everything-for-repair/exported/export.tar.gz
        TEMP_DIR=/tmp/mongo_import

        echo '📦 Распаковка архива...';
        mkdir -p $$TEMP_DIR
        tar -xzf $$ARCHIVE -C $$TEMP_DIR

        echo '📥 Импорт файлов в MongoDB...';
        for $$file in $$TEMP_DIR/*.json; do
          collection=$$(basename $$file .json)
          collection=$${collection//-/_}
          echo \"📥 Импортирование $$file в коллекцию $$collection...\"
          mongoimport --host mongo --db shop-everything-for-repair --collection $$collection --file $$file --jsonArray || true
        done

        echo '✅ Импорт завершен.'
      "

  mongoexport:
    image: mongo:latest
    # depends_on:
    #   - mongoimport
    volumes:
      - ./dump:/dump
    entrypoint: >
      bash -c "
        echo '⏳ Ожидание старта работы MongoDB...';
        sleep 5;
        echo '📤 Экспорт карточек товаров...';
        mongoexport --host mongo --db shop-everything-for-repair --collection product_cards --out /dump/exported/product_cards.json --jsonArray;
        echo '📤 Экспорт карточек акций...';
        mongoexport --host mongo --db shop-everything-for-repair --collection promotion_cards --out /dump/exported/promotion_cards.json --jsonArray;
        echo '📤 Экспорт карточек новостей...';
        mongoexport --host mongo --db shop-everything-for-repair --collection news_cards --out /dump/exported/news_cards.json --jsonArray;
        echo '📤 Сжатие экспортированных файлов в архив export.tar.gz...';
        tar -czf /dump/exported/export.tar.gz -C /dump/exported $(ls /dump/exported | grep -v dump.tar.gz);
        echo '✅ Экспорт завершен.';
      "