version: '3.8'

services:
  backend:
    build: './backend'
    container_name: backend
    restart: 'always'
    ports:
      - '8080:8080'
    depends_on:
      - mongo
      - mongoexport
  
  frontend:
    build: 
      context: './frontend'
      dockerfile: Dockerfile.dev
    container_name: frontend
    restart: 'always'
    ports:
      - '5173:5173'
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
  
  mongo:
    image: mongo:latest
    container_name: my_mongo
    restart: 'always'
    ports:
      - "27017:27017"
    volumes:
      - ./dump:/dump
    command: mongod --bind_ip_all

  mongoimport:
    image: mongo:latest
    depends_on:
      - mongo
    volumes:
      - ./dump:/dump
    entrypoint:
      - /bin/bash
      - -c
      - |
        if [ ! -x /dump/scripts/mongoimport.sh ]; then
          echo "mongoimport.sh not found or not executable" >&2; exit 1;
        fi
        /bin/bash /dump/scripts/mongoimport.sh

  mongoexport:
    image: mongo:latest
    depends_on:
      - mongoimport
    volumes:
      - ./dump:/dump
    entrypoint:
      - /bin/bash
      - -c
      - |
        if [ ! -x /dump/scripts/mongoexport.sh ]; then
          echo "mongoexport.sh not found or not executable" >&2; exit 1;
        fi
        /bin/bash /dump/scripts/mongoexport.sh
